import os
import sys
import subprocess
import tempfile
from app.core.config import settings

async def execute_sandbox_routine(script_contents: str, token: str) -> dict:
    """
    Runs code generated by the agent inside an isolated E2B micro-sandbox.
    Passes the active user's JWT so queries respect multi-tenant RLS boundaries.
    Falls back to a local subprocess execution if E2B_API_KEY is not configured or fails.
    """
    e2b_key = os.getenv("E2B_API_KEY") or getattr(settings, "E2B_API_KEY", "")
    
    # 1. Attempt E2B Sandbox if Key is present
    if e2b_key:
        print("[SANDBOX] E2B API Key found. Initializing cloud sandbox...")
        try:
            from e2b import Sandbox
            
            # Using E2B async/sync manager
            with Sandbox(api_key=e2b_key) as sandbox:
                # Set API endpoint and User Bearer Token context variables
                # Use localhost helper or config strings
                api_url = getattr(settings, "API_V1_STR", "/api/v1")
                # Default to localhost if no production URL is resolved
                base_url = os.getenv("BERAXIS_API_URL", "http://localhost:8000/api/v1")
                
                sandbox.env.set("BERAXIS_API_URL", base_url)
                sandbox.env.set("USER_BEARER_TOKEN", token)
                
                sandbox.filesystem.write("automation.py", script_contents)
                execution = sandbox.process.start("python3 automation.py")
                
                if execution.exit_code != 0:
                    return {
                        "status": "failed",
                        "error": execution.stderr,
                        "exit_code": execution.exit_code,
                        "runner": "e2b"
                    }
                return {
                    "status": "success",
                    "output": execution.stdout,
                    "exit_code": 0,
                    "runner": "e2b"
                }
        except Exception as e:
            print(f"[WARN] E2B initialization failed: {e}. Falling back to local runner.")

    # 2. Local Fallback Runner (Subprocess in temporary directory)
    print("[SANDBOX] Running script in safe local fallback environment...")
    
    # Write to a temp file and execute via a subprocess
    with tempfile.TemporaryDirectory() as tempdir:
        script_path = os.path.join(tempdir, "automation_local.py")
        with open(script_path, "w") as f:
            f.write(script_contents)
            
        # Extract environment variables to pass
        local_env = os.environ.copy()
        local_env["BERAXIS_API_URL"] = os.getenv("BERAXIS_API_URL", "http://localhost:8000/api/v1")
        local_env["USER_BEARER_TOKEN"] = token or ""
        
        try:
            # Run the python process
            result = subprocess.run(
                [sys.executable, script_path],
                env=local_env,
                capture_output=True,
                text=True,
                timeout=10 # Prevent infinite loops
            )
            
            if result.returncode != 0:
                return {
                    "status": "failed",
                    "error": result.stderr or f"Execution failed with code {result.returncode}",
                    "exit_code": result.returncode,
                    "runner": "local_subprocess"
                }
            return {
                "status": "success",
                "output": result.stdout,
                "exit_code": 0,
                "runner": "local_subprocess"
            }
        except subprocess.TimeoutExpired:
            return {
                "status": "failed",
                "error": "Execution timed out (10s limit exceeded).",
                "exit_code": -1,
                "runner": "local_subprocess"
            }
        except Exception as e:
            return {
                "status": "failed",
                "error": str(e),
                "exit_code": -2,
                "runner": "local_subprocess"
            }
